version: 0.1

phases:
  install:
    commands:
      - echo Installing S3 Site
      - npm install s3-site-sync
  build:
    commands:
      - echo Build started on `date`
      - echo Deploying site
      - sudo node s3-site-sync -r -c ./config.js
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - ./**/*.js
    - ./**/*.css
    - ./**/*.html
    - ./**/*.json
