version: 0.1

phases:
  install:
    commands:
      - echo Installing S3 Site
      - npm install -g s3-website
      - sudo mkdir .aws && cd .aws && sudo echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}\nAWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> "credentials"
  build:
    commands:
      - echo Build started on `date`
      - echo Deploying site
      - sudo sudo s3-website deploy -d audiomass-web
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - ./**/*.*
